name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # 為了測試 asyncpg，需要 libpq-dev
        sudo apt-get update && sudo apt-get install -y libpq-dev

    - name: Run tests (using SQLite for CI simplicity)
      # 實際測試時，建議使用 testcontainers 啟動 PostgreSQL，這裡為了快速 CI 使用 SQLite 模擬
      run: |
        # 設置測試專用的環境變數，覆蓋 PostgreSQL URL
        export DATABASE_URL="sqlite+aiosqlite:///./test.db" 
        pytest --cov=app tests/
